name:                linear-fft
version:             0.1.0.0
github:              "konn/linear-fft"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro_at_gmail.com"
copyright:           "2023 (c) Hiromi ISHII"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/linear-fft#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- deepseq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - integer-logarithms
  - linear-array-extra
  - linear-memory
  - linear-parallel
  - linear-witness
  - linear-base
  - linear-generics
  - fmlist
  - optparse-applicative
  - directory
  - filepath

executables:
  linear-fft:
    main:                linear-fft.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N --nonmoving-gc"'
    - -eventlog
    dependencies:
    - linear-fft

tests:
  linear-fft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - '"-with-rtsopts=-N --nonmoving-gc"'
    build-tools:
    - tasty-discover
    dependencies:
    - linear-fft
    - tasty
    - falsify

benchmarks:
  linear-fft-bench:
    main:                bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - '"-with-rtsopts=-N1 --nonmoving-gc"'
    dependencies:
    - linear-fft
    - tasty
    - tasty-bench
    - deepseq
